// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEvYKC8eYEILhbCg_-WXnviDwrAf-iWiM',
    appId: '1:674858142771:web:51dd5497b2fd1b75c7e746',
    messagingSenderId: '674858142771',
    projectId: 'ouagrup86',
    authDomain: 'ouagrup86.firebaseapp.com',
    storageBucket: 'ouagrup86.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASy8uFgkea1Iq0v0XbSnp_DhJ12r5mX9A',
    appId: '1:674858142771:android:c71a8e1e9c14bd92c7e746',
    messagingSenderId: '674858142771',
    projectId: 'ouagrup86',
    storageBucket: 'ouagrup86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAWhr9ZIepdBm29ypwaFpik17u2UrnE7o',
    appId: '1:674858142771:ios:1891960abdbbc2c7c7e746',
    messagingSenderId: '674858142771',
    projectId: 'ouagrup86',
    storageBucket: 'ouagrup86.appspot.com',
    iosBundleId: 'com.example.ouaBootcamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAWhr9ZIepdBm29ypwaFpik17u2UrnE7o',
    appId: '1:674858142771:ios:1891960abdbbc2c7c7e746',
    messagingSenderId: '674858142771',
    projectId: 'ouagrup86',
    storageBucket: 'ouagrup86.appspot.com',
    iosBundleId: 'com.example.ouaBootcamp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEvYKC8eYEILhbCg_-WXnviDwrAf-iWiM',
    appId: '1:674858142771:web:2118e2d8be16165ec7e746',
    messagingSenderId: '674858142771',
    projectId: 'ouagrup86',
    authDomain: 'ouagrup86.firebaseapp.com',
    storageBucket: 'ouagrup86.appspot.com',
  );
}
